---
title: "The Stanford Open Policing Project"
author: "Oleksiy Anokhin"
date: "March 23, 2019"
output: html_document
---

```{r, packages, echo = FALSE, message = FALSE, warning = FALSE}
# Install packages 
library(tidyverse)
library(ggthemes)
# Disable scientific notation
options(scipen = 999)
```

This small project is a part of a weekly [**#TidyTuesday**](https://github.com/rfordatascience/tidytuesday) challenge and uses [**The Stanford Open Policing Project**](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-03-19) data. More information about the project in this [video](https://www.youtube.com/watch?v=iwOWcuFjNfw)

I decided to analyze information abput traffic stops by police in Albany, NY, because I lived in New State. 
Albany data contains 10328 police stops of Albany drivers between Decemeber 2007 and December 2017. 

<center>
```{r, race, echo = FALSE, message = FALSE, warning = FALSE}
albany_data <- read_rds("albany_data.rds")

# Filter by race
albany_stops_by_race <- albany_data %>% group_by(subject_race) %>% summarise(number = n())

# Visualize a number of stops by race
ggplot(albany_stops_by_race, aes(reorder(subject_race, number), number, fill = subject_race)) + geom_bar(stat = "identity", color  = "black") +
  theme_tufte() +
  theme(axis.title.y = element_blank()) +
  theme(axis.title.x = element_blank()) +
  theme(legend.position = "none")
```
</center>

<center>
```{r, age, echo = FALSE, message = FALSE, warning = FALSE}
ggplot(albany_data, aes(subject_race, subject_age, fill = subject_race)) + geom_boxplot() +
  theme_tufte() +
  theme(axis.title.y = element_blank()) +
  theme(axis.title.x = element_blank()) +
  theme(legend.position = "none")
```
</center>

<center>
```{r, hour, echo = FALSE, message = FALSE, warning = FALSE}
albany_data$time <- strptime(albany_data$time, "%H:%M:%S")
albany_data$time <- as.integer(format(albany_data$time, "%H"))

ggplot(albany_data, aes(time, fill = subject_race)) + geom_histogram(binwidth = 1, color = "black", alpha = 0.8) +
  scale_x_continuous(breaks = seq(0, 23, 1)) + 
  theme_tufte() +
  theme(axis.title.y = element_blank()) +
  theme(axis.title.x = element_blank()) +
  theme(legend.title = element_blank()) +
  theme(legend.position = "bottom") + 
  ylim(0, 8000)
```
</center>
